server:
  port: 8081
spring:
  application:
    name: dear_telangana
  datasource:
    username: keycloak
    password: keycloak
    url: jdbc:postgresql://localhost:5432/keycloak
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
com:
  data: shiva

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: loggers